#!/usr/bin/env bash
# Build the image, smoke test it, and write the release runbook for the version
# that package.json holds. Every check runs before the runbook is written, so a
# failed check leaves no instructions behind.
#
# Usage: generate-publishing-instructions.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

SEMVER_PRERELEASE_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+-[0-9A-Za-z.]+$'
IMAGE_REPO='ghcr.io/couimet/rabbit-maximizer'
VERIFY_IMAGE_REF='rabbit-maximizer:release'
VERIFY_ENV_FILE='.env.ci'
PACKAGE_FILE="$PROJECT_ROOT/package.json"
CHANGELOG_FILE="$PROJECT_ROOT/CHANGELOG.md"
OUTPUT_DIR="$PROJECT_ROOT/publishing-instructions"

git_in_project() {
  (cd "$PROJECT_ROOT" && git "$@")
}

read_package_version() {
  sed -n 's/^[[:space:]]*"version": "\([^"]*\)".*/\1/p' "$PACKAGE_FILE" | head -n 1
}

fail() {
  echo "FAIL: $1: $2" >&2
  exit 1
}

if ! git_in_project rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  fail 'git working tree' "$PROJECT_ROOT is not a git working tree"
fi

if [ -n "$(git_in_project status --porcelain)" ]; then
  fail 'clean working tree' 'commit the pending changes first'
fi

VERSION="$(read_package_version)"

if [ -z "$VERSION" ]; then
  fail 'package version' 'package.json holds no version field'
fi

if [[ "$VERSION" =~ $SEMVER_PRERELEASE_PATTERN ]]; then
  fail 'stable version' "package.json holds the prerelease '$VERSION'; this runbook covers stable releases only"
fi

RELEASE_TAG="v$VERSION"

if git_in_project rev-parse --verify --quiet "refs/tags/$RELEASE_TAG" > /dev/null; then
  fail 'unused release tag' "the tag $RELEASE_TAG already exists"
fi

if ! grep -q -F -- "## [$VERSION]" "$CHANGELOG_FILE"; then
  fail 'changelog heading' "CHANGELOG.md holds no '## [$VERSION]' heading; run pnpm release:lock first"
fi

if ! grep -q -F -- "[$VERSION]:" "$CHANGELOG_FILE"; then
  fail 'changelog reference link' "CHANGELOG.md holds no '[$VERSION]:' reference link"
fi

COMMIT_SHA="$(git_in_project rev-parse HEAD)"

echo "Building $VERIFY_IMAGE_REF from $COMMIT_SHA..."
docker build -t "$VERIFY_IMAGE_REF" "$PROJECT_ROOT" \
  || fail 'image build' "docker build refused the tree at $COMMIT_SHA"

echo 'Smoke testing the image...'
IMAGE_REF="$VERIFY_IMAGE_REF" ENV_FILE="$PROJECT_ROOT/$VERIFY_ENV_FILE" \
  bash "$PROJECT_ROOT/scripts/docker/smoke-test.sh" \
  || fail 'smoke test' "scripts/docker/smoke-test.sh refused $VERIFY_IMAGE_REF"

# The tags come from the script the publish workflow reads, so the runbook and
# the workflow cannot disagree about what the release publishes.
TAGS_OUTPUT="$(cd "$PROJECT_ROOT" && \
  EVENT_NAME='release' RELEASE_TAG="$RELEASE_TAG" IS_PRERELEASE='false' \
  IMAGE_REPO="$IMAGE_REPO" SHA="$COMMIT_SHA" \
  bash "$PROJECT_ROOT/scripts/docker/derive-image-tags.sh")"
PUBLISHED_TAGS="$(printf '%s\n' "$TAGS_OUTPUT" | sed -n 's|^tags=||p')"

if [ -z "$PUBLISHED_TAGS" ]; then
  fail 'published tags' "scripts/docker/derive-image-tags.sh printed no tags for $RELEASE_TAG"
fi

TAG_NAMES=''
MANIFEST_COMMANDS=''
while IFS= read -r tag_ref; do
  TAG_NAMES="${TAG_NAMES:+$TAG_NAMES, }${tag_ref#"$IMAGE_REPO:"}"
  MANIFEST_COMMANDS="$MANIFEST_COMMANDS
docker manifest inspect $tag_ref"
done < <(printf '%s\n' "$PUBLISHED_TAGS" | tr ',' '\n')

mkdir -p "$OUTPUT_DIR"
OUTPUT_FILE="$OUTPUT_DIR/publish-$RELEASE_TAG.md"

cat > "$OUTPUT_FILE" <<RUNBOOK
# Release $RELEASE_TAG

Generated by \`pnpm release:instructions\` from commit \`$COMMIT_SHA\` on $(date -u +%Y-%m-%d).

The image repository is \`$IMAGE_REPO\`. This release publishes these tags: $TAG_NAMES.

## 1. Smoke test the image

Done. The generator built \`$VERIFY_IMAGE_REF\` from this commit and ran \`pnpm docker:smoke-test\` against \`$VERIFY_ENV_FILE\`. The entrypoint refused to start without a data mount, the dashboard answered on \`/api/summary\`, and the container stopped cleanly.

## 2. Create the tag

\`\`\`bash
git tag -a $RELEASE_TAG -m "$RELEASE_TAG"
git push origin $RELEASE_TAG
\`\`\`

## 3. Create the release

Copy the \`## [$VERSION]\` section of \`CHANGELOG.md\` into \`/tmp/$RELEASE_TAG-notes.md\` first. Then run:

\`\`\`bash
gh release create $RELEASE_TAG --title "$RELEASE_TAG" --notes-file /tmp/$RELEASE_TAG-notes.md
\`\`\`

Do not pass \`--prerelease\`. This version is stable.

## 4. Wait for the publish workflow and verify the published tags

The workflow refuses a commit whose checks did not pass, so a failure here means the tag points at a red commit.

\`\`\`bash
gh run list --workflow publish-image.yml --limit 1
gh run watch <run-id>
\`\`\`

Then confirm that every tag answers through an anonymous pull:

\`\`\`bash$MANIFEST_COMMANDS
\`\`\`

A \`docker manifest inspect\` that asks for credentials means the GHCR package is still private. See the release notes in \`PUBLISHING.md\`.

## 5. Pull and run the image

\`\`\`bash
docker pull $IMAGE_REPO:$VERSION
\`\`\`

Start the container as the "Run with Docker" section of \`README.md\` describes, with \`$IMAGE_REPO:$VERSION\` in place of the pinned tag. Read the "Upgrading" section of that file before you replace a running container.

## 6. Commit the runbook

\`publishing-instructions/publish-$RELEASE_TAG.md\` belongs to the repository, so the release keeps the record of what it ran.

\`\`\`bash
git add publishing-instructions/publish-$RELEASE_TAG.md
git commit -m "Record the $RELEASE_TAG release runbook"
git push
\`\`\`
RUNBOOK

echo "Wrote $OUTPUT_FILE"
