/**
 * Rabbit Maximizer error codes.
 *
 * Architecture principles:
 * - No ERR_ prefix: If defined here, it's an error
 * - Values are descriptive strings (same as keys) for clear context in logs
 * - Core errors stay English (industry standard — like TypeScript/Git/JavaScript)
 *
 * Please keep alphabetical order for ease of maintenance.
 */
export enum RabbitMaximizerErrorCodes {
  CONFIG_VALIDATION_FAILED = 'CONFIG_VALIDATION_FAILED',

  GITHUB_API_ERROR = 'GITHUB_API_ERROR',
  GITHUB_AUTH_ERROR = 'GITHUB_AUTH_ERROR',
  GITHUB_NOT_FOUND = 'GITHUB_NOT_FOUND',
  GITHUB_RATE_LIMITED = 'GITHUB_RATE_LIMITED',
  PRISMA_CONNECTION_METHOD_NOT_SUPPORTED = 'PRISMA_CONNECTION_METHOD_NOT_SUPPORTED',

  QUEUE_ITEM_NOT_PENDING = 'QUEUE_ITEM_NOT_PENDING',

  RETRIGGER_STALE_COMMENT_REPLACEMENT_DELETED = 'RETRIGGER_STALE_COMMENT_REPLACEMENT_DELETED',
  RETRIGGER_STALE_COMMENT_RESCHEDULE = 'RETRIGGER_STALE_COMMENT_RESCHEDULE',
  RETRIGGER_STALE_COMMENT_SKIP = 'RETRIGGER_STALE_COMMENT_SKIP',

  SERVER_ADDRESS_NOT_AVAILABLE = 'SERVER_ADDRESS_NOT_AVAILABLE',

  TOKEN_VALIDATION_EMPTY_FILTER = 'TOKEN_VALIDATION_EMPTY_FILTER',
}
