import { SoftDeleteConfig, softDeleteExtension } from '../../src/index.js';

import { afterAll, beforeAll, describe, expect, it } from '@jest/globals';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';
import { execFileSync } from 'child_process';
import { mkdtempSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';

const ACTIVE_LABEL = 'active';
const SCHEMA_PATH = join(import.meta.dirname, 'schema.prisma');
const MODEL = 'TestEntity';

describe('softDeleteExtension (integration)', () => {
  let tmpDir: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let prisma: any;

  beforeAll(async () => {
    tmpDir = mkdtempSync(join(tmpdir(), 'soft-delete-test-'));
    const dbPath = join(tmpDir, 'test.db');
    execFileSync('npx', ['prisma', 'db', 'push', '--schema', SCHEMA_PATH, '--force-reset', '--accept-data-loss'], {
      env: { ...process.env, DATABASE_URL: `file:${dbPath}` },
      stdio: 'pipe',
    });
    execFileSync('npx', ['prisma', 'generate', '--schema', SCHEMA_PATH, '--no-hints'], { stdio: 'pipe' });
    // @ts-expect-error — generated by prisma generate at runtime, does not exist at compile time
    const { PrismaClient } = await import('./generated/index.js');
    const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
    prisma = new PrismaClient({ adapter }).$extends(softDeleteExtension({ models: { [MODEL]: true } }));
  });

  afterAll(async () => {
    await prisma.$disconnect();
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('filters out soft-deleted rows from findFirst', async () => {
    const row = await prisma.testEntity.create({ data: { label: 'deleted', is_not_deleted: null, deleted_at: new Date() } });
    const result = await prisma.testEntity.findFirst({ where: { id: row.id } });
    expect(result).toBeNull();
  });

  it('returns active rows from findFirst', async () => {
    const row = await prisma.testEntity.create({ data: { label: ACTIVE_LABEL, is_not_deleted: true } });
    const result = await prisma.testEntity.findFirst({ where: { id: row.id } });
    expect(result).not.toBeNull();
    expect(result.label).toBe(ACTIVE_LABEL);
  });

  it('filters out soft-deleted rows from findMany', async () => {
    const active = await prisma.testEntity.create({ data: { label: 'a', is_not_deleted: true } });
    await prisma.testEntity.create({ data: { label: 'd', is_not_deleted: null, deleted_at: new Date() } });
    const results = await prisma.testEntity.findMany();
    expect(results).toHaveLength(2); // 2 active total: 'active' + 'a'
    expect(results.some((r: { id: number }) => r.id === active.id)).toBe(true);
  });

  it('count ignores soft-deleted rows', async () => {
    const result = await prisma.testEntity.count();
    expect(result).toBe(2);
  });
});

describe('SoftDeleteConfig', () => {
  it('uses default column names', () => {
    const cfg = new SoftDeleteConfig();
    expect(cfg.activeFilter).toStrictEqual({ is_not_deleted: true });
    expect(cfg.activeMarker).toStrictEqual({ is_not_deleted: true });
    expect(cfg.softDeleteMarker()).toStrictEqual({
      is_not_deleted: null,
      deleted_at: expect.any(Date),
    });
  });

  it('accepts custom column names', () => {
    const cfg = new SoftDeleteConfig({ isNotDeletedColumn: 'active', deletedAtColumn: 'removed_at' });
    expect(cfg.activeFilter).toStrictEqual({ active: true });
    expect(cfg.activeMarker).toStrictEqual({ active: true });
    expect(cfg.softDeleteMarker()).toStrictEqual({
      active: null,
      removed_at: expect.any(Date),
    });
  });
});
