/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getQueue'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: string;
    };
    /** @enum {string} */
    QueueStatus: 'pending' | 'posted' | 'completed' | 'failed';
    QueueItem: {
      id: number;
      uuid: string;
      repo_full_name: string;
      pr_number: number;
      status: components['schemas']['QueueStatus'];
      /** Format: date-time */
      scheduled_for: string;
      attempts: number;
      source_comment_url?: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    /** @enum {string} */
    EventType: 'detected' | 'enqueued' | 'posted' | 'rejected' | 'completed' | 'failed';
    EventEntry: {
      id: number;
      uuid: string;
      /** Format: date-time */
      ts: string;
      type: components['schemas']['EventType'];
      repo_full_name: string;
      pr_number: number;
      correlation_id: string;
      request_id?: string;
      version: string;
      metadata?: Record<string, never>;
      payload: Record<string, never>;
    };
    QueueCounts: {
      pending: number;
      posted: number;
      completed: number;
      failed: number;
    };
    EventCounts: {
      detected: number;
      enqueued: number;
      posted: number;
      rejected: number;
      completed: number;
      failed: number;
    };
    Summary: {
      queueCounts: components['schemas']['QueueCounts'];
      eventCounts24h: components['schemas']['EventCounts'];
      oldestPending: components['schemas']['QueueItem'] | null;
    };
    PaginatedQueue: {
      data: components['schemas']['QueueItem'][];
      total: number;
      page: number;
      pageSize: number;
    };
    PaginatedEvents: {
      data: components['schemas']['EventEntry'][];
      total: number;
      page: number;
      pageSize: number;
    };
  };
  responses: {
    /** @description Unexpected server error */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getSummary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Aggregate status summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Summary'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getQueue: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated queue items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedQueue'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getEvents: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedEvents'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
}
