/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getQueue'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getQueueOrder'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue/order/move': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['moveQueueOrder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue/order/move-to-top': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['moveToTop'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getConfig'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dashboard-state': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getDashboardState'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue/{uuid}/mark-completed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['markCompleted'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue/{uuid}/retrigger-now': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['retriggerNow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue/triggered': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getTriggered'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/pause': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['setPaused'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/state/next_review_available_at': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getNextReviewAvailable'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: string;
    };
    /** @enum {string} */
    QueueStatus: 'pending' | 'retriggered' | 'completed' | 'failed';
    QueueItem: {
      id: number;
      uuid: string;
      repo_full_name: string;
      pr_number: number;
      pr_title: string;
      status: components['schemas']['QueueStatus'];
      /**
       * Format: date-time
       * @description Eligibility gate — item cannot be processed before this timestamp
       */
      not_before: string;
      attempts: number;
      source_comment_url?: string;
      /** @enum {string} */
      trigger_source: 'dashboard_retrigger_now' | 'scheduler';
      retrigger_comment_url?: string | null;
      /** Format: date-time */
      retriggered_at?: string | null;
      /** Format: date-time */
      failed_at?: string | null;
      /** Format: date-time */
      completed_at?: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    /** @enum {string} */
    EventType: 'detected' | 'enqueued' | 'retriggered' | 'bypassed' | 'completed' | 'failed';
    EventEntry: {
      id: number;
      uuid: string;
      /** Format: date-time */
      ts: string;
      type: components['schemas']['EventType'];
      repo_full_name: string;
      pr_number: number;
      correlation_id: string;
      request_id?: string;
      version: string;
      metadata?: {
        [key: string]: unknown;
      };
      payload: {
        [key: string]: unknown;
      };
    };
    QueueCounts: {
      pending: number;
      retriggered: number;
      failed: number;
    };
    EventCounts: {
      detected: number;
      enqueued: number;
      retriggered: number;
      failed: number;
    };
    DashboardState: {
      /** Format: date-time */
      nextReviewAvailableAt: string | null;
      pendingItems: components['schemas']['QueueItem'][];
      eventCounts: components['schemas']['EventCounts'];
      paused: boolean;
    };
    PauseRequest: {
      paused: boolean;
    };
    PauseResponse: {
      paused: boolean;
    };
    PublicConfig: {
      pauseNotificationInitialDelayMinutes: number;
      pauseNotificationRepeatIntervalMinutes: number;
    };
    Summary: {
      queueCounts: components['schemas']['QueueCounts'];
      eventCounts: components['schemas']['EventCounts'];
      oldestPending: components['schemas']['QueueItem'] | null;
    };
    PaginatedQueue: {
      data: components['schemas']['QueueItem'][];
      total: number;
      page: number;
      pageSize: number;
    };
    PaginatedEvents: {
      data: components['schemas']['EventEntry'][];
      total: number;
      page: number;
      pageSize: number;
    };
    MoveToTopRequest: {
      queueItemUuid: string;
    };
    QueueOrderMoveRequest: {
      queueItemIds: number[];
      /** @enum {string} */
      direction: 'up' | 'down';
    };
    QueueOrderResponse: {
      data: components['schemas']['QueueItem'][];
    };
    StateResponse: {
      /** Format: date-time */
      next_review_available_at: string | null;
    };
  };
  responses: {
    /** @description Unexpected server error */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getSummary: {
    parameters: {
      query?: {
        duration?: '24h' | '2d' | '3d' | '5d' | '1w';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Aggregate status summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Summary'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getQueue: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated queue items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedQueue'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getQueueOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pending items in effective order */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QueueOrderResponse'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  moveQueueOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QueueOrderMoveRequest'];
      };
    };
    responses: {
      /** @description Updated effective order after move */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QueueOrderResponse'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Queue items not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  moveToTop: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MoveToTopRequest'];
      };
    };
    responses: {
      /** @description Item moved to top of queue */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Queue item not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Item is not pending */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getEvents: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedEvents'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public client-facing configuration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicConfig'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getDashboardState: {
    parameters: {
      query?: {
        duration?: '24h' | '2d' | '3d' | '5d' | '1w';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dashboard state */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardState'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  markCompleted: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item marked completed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            ok: boolean;
          };
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Queue item not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  retriggerNow: {
    parameters: {
      query?: {
        overridePause?: boolean;
      };
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retrigger posted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Queue item not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Scheduler is paused, item is not pending, or trigger failed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getTriggered: {
    parameters: {
      query: {
        since: string;
        page?: number;
        pageSize?: number;
        include_completed?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated triggered items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedQueue'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  setPaused: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PauseRequest'];
      };
    };
    responses: {
      /** @description Pause state updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PauseResponse'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getNextReviewAvailable: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Next review availability timestamp */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StateResponse'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
}
