name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    uses: couimet/github-actions/.github/workflows/typescript-ci-checks.yml@main
    permissions:
      contents: read
      pull-requests: write
    with:
      test-command: 'cp .env.ci .env && pnpm test'
